import {
    createUser,
    findUserEmail,
    findUserToken,
    createAdminUser,
    findAdminUsers,
    findAdminUserToken,
    updateUser,
    updateAdminUser,
    findAdminToken
} from './User/user'

import  {
    updateProduct,
    findProduct,
    addProduct,
    allProduct,
    deleteProduct,
    findByIdProduct,
    findAdminProduct,
    adminProductAdd,
    allAdminProduct,
    findByIdAdminProduct,
    deleteAdminProduct,
    addUserProduct,
    findUserCategory,
    addUserCategory,
    deleteUserProduct,
    findUserProduct,
    updateUserProduct,
    allUserCategory,
    deleteUserCategory,
    allUserProduct,
    userProductAddBasket,
    deleteUserProductBasket,
    adminProductAddBasket,
    deleteAdminProductBasket,
    productAddBasket,
    deleteProductBasket,
    postPayment
} from './Product/product'

export const UserServices = {
    createUser,
    findUserEmail,
    findUserToken,
    createAdminUser,
    findAdminUsers,
    findAdminUserToken,
    updateUser,
    updateAdminUser,
    findAdminToken,
}
export const ProductService = {
    updateProduct,
    addProduct,
    findProduct,
    allProduct,
    deleteProduct,
    findByIdProduct,
    findAdminProduct,
    adminProductAdd,
    allAdminProduct,
    findByIdAdminProduct,
    deleteAdminProduct,
    addUserProduct,
    addUserCategory,
    allUserCategory,
    deleteUserCategory,
    allUserProduct,
    userProductAddBasket,
    deleteUserProductBasket,
    adminProductAddBasket,
    deleteAdminProductBasket,
    productAddBasket,
    deleteProductBasket,
    postPayment
}